data : 
    raw_path : 'data/raw' 
    processed_path : "data/processed" 
    ocr_file_path: "data/ocr_temp_images"

memory : 
    sqlite_database_path : 'data/memory.db'
    limit : 3
    
rag_core : 
    chunking : 
        chunk_size: 1000
        chunk_overlap: 100
    embedding:
        model_name: "sentence-transformers/all-MiniLM-L6-v2"
    database:
        persist_directory: "data/vector_store"
        collection_name: "study_notes"
    retriever:
        k: 5
    generator:
        llm_name: "mistralai/Mistral-7B-Instruct-v0.3" 

features:
    quiz:
        similarity_threshold: 0.85